# fly.toml app configuration file generated for luckydart on 2023-05-24T15:16:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "luckydart"
primary_region = "mad"

[env]
  VITE_FRONTEND_URI = "https://web3-roulette.fly.dev"
  VITE_GOOGLE_OAUTH_URI = "https://www.googleapis.com/oauth2/v1/"
  VITE_API_URI = "http://localhost:3000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
