name: Automatic Fly.io Deployer (API)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.node.toml --dockerfile packages/node-app/node.Dockerfile .
        env: 
          FLY_API_TOKEN: fo1_PMKcQwvptQfhonPQsjGLJnSJt90kY-Aqx80Z_qrKb24